CREATE TABLE snapshot(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   data_uri TEXT NOT NULL,
-- YYYY-MM-DD HH:MM:SS
   created_at TEXT NOT NULL
);

CREATE TABLE tag_group(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   name TEXT NOT NULL
);

CREATE TABLE tag(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   tag_group_id INTEGER NOT NULL,
   value TEXT
);

CREATE TABLE snapshot_tag(
   id INTEGER PRIMARY KEY AUTOINCREMENT,
   snapshot_id INTEGER NOT NULL,
   tag_id INTEGER NOT NULL
);
